### ISSUE TITLE
Ubuntu 22.04.3 LTS uses zstd compression instead of lz4

### ISSUE THREAD

**Issue by catharsis71** [bitfolk/decompress-lz4-kernels#1]
Hello,

Ubuntu 22 LTS has switched the kernel compression method to "zstd" which Xen also has issues with

Could you potentially modify this to handle "zstd" kernels as well?

extract-vmlinux handles "zstd" fine so I can run it manually but it would be nice to have the hook

**Comment by grifferz** [comment]
Hi,

On Sun, Aug 13, 2023 at 01:24:09PM -0700, catharsis71 wrote:
> Could you potentially modify this to handle "zstd" kernels as well?

I suppose I could but I basically regard this as legacy software for
versions of Ubuntu that don't support PVH mode Xen. 20.04 and beyond
boot under PVH mode using the GRUB PVH images so it doesn't matter
what kernel compression is used.

Is there a reason you can't use PVH mode?

**Comment by catharsis71** [comment]
I use some random VPS provider that hasn't updated their Xen in a long time and isn't really communicative; through experimentation I found that their system will boot LZ4 but won't boot ZSTD.  I don't have any visibility into their infrastructure beyond that.

But anyway I got it working on my own, just had to search/replace "lz4" for "zstd"  and change the pattern to '(\265/\375'
